#!/usr/bin/python3

import argparse
import json
import re2 as r

def convert_to_ndjson(input_file, output_file):
    with open(input_file) as f:
        input_data = [json.loads(line) for line in f]

    with open(output_file, 'w') as output:
        for data in input_data:
            name = data.get('package_name')
            repo = data.get('package_repo')
            ecosys = data.get ('package_ecosystem')

            if name is None:
                continue

            if not bool(r.match(r'^https?://github\.com/', repo)):
                continue

            license_info = data.get('package_licenses')

            # Handle null or empty lists for licenses
            if license_info in (None, []):
                license_info = None
            else:
                license_info = license_info.get('Normalised License')

            language = data.get('package_language')
            valid = True

            final_json = {
                "name": name,
                "repo": repo,
                "license": license_info,
                "language": language,
                "valid": valid,
                "ecosystem": ecosys
            }

            output.write(json.dumps(final_json) + "\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert input JSON data to NDJSON format.")
    parser.add_argument("input_file", help="Path to the input data file.")
    parser.add_argument("output_file", help="Path to the output NDJSON file.")

    args = parser.parse_args()

    convert_to_ndjson(args.input_file, args.output_file)
